### ISSUE TITLE
Extremely bad performance 

### ISSUE THREAD

**Issue by PaulMndn** [sneakyevil/Demo-Viewer#7]
The performance of this app has gotten incredible bad over the last half year/8 months. I used to run fine, now after loading any file, no matter how small, I only get 1 frame every 2-3 seconds. And that's before I actually start the replay. This is unusable. 
It also uses up all my memory. 

I do know my laptop is not very powerful, but it used to run perfectly fine.

---
My Specs:
- Core i3-8130U
- Intel UHD Graphics 620
- 8 GB RAM
- Replay Viewer v1.10.3 (Oculus store version)

**Comment by PaulMndn** [comment]
this is very unfortunate because I really liked using those replays to record matches and scrims.

**Comment by NtsFranz** [comment]
This seems like a bug despite your hardware.
Could you try this example file to see if it's a file size issue?
https://echopedia.gg/images/8/80/Clip_2021-08-28_23-11-51.echoreplay

What arena model are you using? The default one (Arena V4) is much heavier than the others.

**Comment by PaulMndn** [comment]
I have been using Arena V4 but also tried the others which also lagged.

When I try it now though, for some reason it does not lag anymore and runs quite good. But crashes after some time. What I also noticed is that if I open the program by double clicking a larger file it crashes while loading if I move the camera too much.

I have not found a way to reliably reproduce the chrashes yet, but it only happenes with large files (the ones I've tried were around 200 MB compressed) and only after some time so I think it has something to do with loading the file into memory. 
Maybe it crashes when it runs out of free memory? In that case a possible fix would be to load and unload it more dynamically according to the available memory. (Don't know if it might do that already)

**Comment by NtsFranz** [comment]
200MB compressed means the uncompressed file is around 2GB, which is quite large.
The actually memory usage is even worse than that, since the program saves a parsed version in memory for each frame as well. This wasn't really a concern for the size of files I had thought would occur. 
It would certainly be possible to use a streaming approach where the whole file isn't loaded into memory, but this would come at the cost of scrubbing performance. With the use of the upcoming .butter file format I will take another look at this, since reading performance is about 10x faster with that file format than with .echoreplay.

**Comment by PaulMndn** [comment]
I will close this issue as it seems like it fixed itself. Even with big files.
